In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/sahaay-dc-training-assignment-8-part-2/sample_submission.csv
/kaggle/input/sahaay-dc-training-assignment-8-part-2/train.csv
/kaggle/input/sahaay-dc-training-assignment-8-part-2/test.csv


In [2]:
df_train = pd.read_csv('/kaggle/input/sahaay-dc-training-assignment-8-part-2/train.csv')
df_test = pd.read_csv('/kaggle/input/sahaay-dc-training-assignment-8-part-2/test.csv')

In [3]:
df_train

row_ID target  landmark_0_x  landmark_0_y  landmark_0_z  landmark_1_x  \
0           0      A      0.428278      0.524772 -2.572420e-07      0.484400   
1           1      A      0.304148      0.531148 -4.656498e-07      0.421171   
2           2      A      0.391625      0.446599 -2.811430e-07      0.445145   
3           3      A      0.390276      0.406045 -2.853174e-07      0.456652   
4           4      A      0.353765      0.388102 -4.312182e-07      0.445609   
...       ...    ...           ...           ...           ...           ...   
22111   22111      L      0.307203      0.882864 -2.191121e-07      0.495807   
22112   22112      L      0.374179      0.908869 -2.208564e-07      0.547471   
22113   22113      L      0.355818      0.843392 -3.780697e-08      0.498642   
22114   22114      L      0.511802      0.922995 -4.084476e-07      0.623022   
22115   22115      L      0.234741      0.818666 -2.245653e-07      0.447325   

       landmark_1_y  landmark_1_z  landmark_2_x  landmark_2_y  ...  \
0          0.516362     -0.018880      0.532799      0.455504  ...   
1          0.507409     -0.039727      0.517571      0.339937  ...   
2          0.441418     -0.012155      0.488408      0.396603  ...   
3          0.393167     -0.027606      0.514125      0.302133  ...   
4          0.364787     -0.037346      0.520186      0.247980  ...   
...             ...           ...           ...           ...  ...   
22111      0.794279     -0.064358      0.633977      0.641007  ...   
22112      0.786441     -0.066584      0.656398      0.614672  ...   
22113      0.737645     -0.118579      0.587279      0.593741  ...   
22114      0.725270     -0.075638      0.663013      0.543557  ...   
22115      0.769973     -0.053270      0.595556      0.662694  ...   

       landmark_17_z  landmark_18_x  landmark_18_y  landmark_18_z  \
0          -0.003415       0.438880       0.360585      -0.026516   
1          -0.017070       0.292822       0.165031      -0.075076   
2          -0.004553       0.413538       0.305595      -0.020640   
3          -0.008726       0.386480       0.192042      -0.037925   
4          -0.010648       0.349854       0.101842      -0.052645   
...              ...            ...            ...            ...   
22111      -0.027636       0.197981       0.447619      -0.089146   
22112      -0.026257       0.193233       0.500218      -0.084771   
22113       0.009978       0.146249       0.405611      -0.025794   
22114      -0.000029       0.188823       0.616563      -0.060169   
22115      -0.028838       0.244535       0.384371      -0.085185   

       landmark_19_x  landmark_19_y  landmark_19_z  landmark_20_x  \
0           0.432223       0.408768      -0.022789       0.426714   
1           0.291675       0.281630      -0.068730       0.291000   
2           0.407231       0.344205      -0.015772       0.400575   
3           0.384629       0.258377      -0.031777       0.382332   
4           0.347607       0.190299      -0.046337       0.345274   
...              ...            ...            ...            ...   
22111       0.244449       0.564507      -0.059462       0.267776   
22112       0.260758       0.604421      -0.054870       0.294919   
22113       0.190220       0.495869       0.005848       0.227028   
22114       0.278721       0.690078      -0.037538       0.337994   
22115       0.260783       0.503112      -0.047653       0.264900   

       landmark_20_y  landmark_20_z  
0           0.444198      -0.011816  
1           0.361742      -0.043297  
2           0.373929      -0.006263  
3           0.304489      -0.016415  
4           0.252969      -0.026332  
...              ...            ...  
22111       0.630822      -0.021899  
22112       0.662821      -0.017909  
22113       0.538356       0.043086  
22114       0.721469      -0.005339  
22115       0.563205      -0.003443  

[22116 rows x 65 columns]

In [4]:
df_train.isnull().sum()

row_ID           0
target           0
landmark_0_x     0
landmark_0_y     0
landmark_0_z     0
                ..
landmark_19_y    0
landmark_19_z    0
landmark_20_x    0
landmark_20_y    0
landmark_20_z    0
Length: 65, dtype: int64

In [5]:
df_test.isnull().sum()

row_ID           0
landmark_0_x     9
landmark_0_y     9
landmark_0_z     9
landmark_1_x     9
                ..
landmark_19_y    9
landmark_19_z    9
landmark_20_x    9
landmark_20_y    9
landmark_20_z    9
Length: 64, dtype: int64

In [6]:
df_train.describe()

row_ID  landmark_0_x  landmark_0_y  landmark_0_z  landmark_1_x  \
count  22116.000000  22116.000000  22116.000000  2.211600e+04  22116.000000   
mean   11057.500000      0.534695      0.718224  2.454822e-07      0.606236   
std     6384.483613      0.182420      0.156182  7.601960e-07      0.173763   
min        0.000000      0.011036      0.046088 -2.170626e-06      0.046916   
25%     5528.750000      0.407792      0.608351 -3.139884e-07      0.484866   
50%    11057.500000      0.537728      0.742217  2.277275e-07      0.619609   
75%    16586.250000      0.669866      0.838124  8.455049e-07      0.736401   
max    22115.000000      1.036187      1.077772  2.762093e-06      1.039599   

       landmark_1_y  landmark_1_z  landmark_2_x  landmark_2_y  landmark_2_z  \
count  22116.000000  22116.000000  22116.000000  22116.000000  22116.000000   
mean       0.655724     -0.045427      0.634859      0.557198     -0.063140   
std        0.155146      0.035673      0.165142      0.152388      0.048409   
min        0.077325     -0.275893     -0.014095      0.075592     -0.510218   
25%        0.545928     -0.064386      0.530136      0.446692     -0.086773   
50%        0.674779     -0.046255      0.650125      0.566629     -0.062292   
75%        0.772596     -0.028446      0.754104      0.668911     -0.039059   
max        1.025485      0.228886      1.011568      0.974953      0.298393   

       ...  landmark_17_z  landmark_18_x  landmark_18_y  landmark_18_z  \
count  ...   22116.000000   22116.000000   22116.000000   22116.000000   
mean   ...      -0.041783       0.439311       0.479189      -0.085800   
std    ...       0.039001       0.165938       0.175526       0.056799   
min    ...      -0.566762      -0.011155      -0.004075      -0.716663   
25%    ...      -0.056986       0.319342       0.349302      -0.113142   
50%    ...      -0.036708       0.436198       0.472915      -0.078586   
75%    ...      -0.020396       0.564747       0.603377      -0.046072   
max    ...       0.175158       1.049330       1.036233       0.168540   

       landmark_19_x  landmark_19_y  landmark_19_z  landmark_20_x  \
count   22116.000000   22116.000000   22116.000000   22116.000000   
mean        0.468796       0.488217      -0.084136       0.489761   
std         0.174215       0.193499       0.056641       0.185084   
min        -0.017567      -0.008888      -0.754320      -0.054246   
25%         0.343821       0.336635      -0.110051       0.357557   
50%         0.471375       0.485675      -0.077159       0.493386   
75%         0.601074       0.633174      -0.045696       0.631340   
max         1.073180       1.026268       0.144692       1.095235   

       landmark_20_y  landmark_20_z  
count   22116.000000   22116.000000  
mean        0.498231      -0.071261  
std         0.214981       0.053751  
min        -0.076664      -0.802696  
25%         0.332819      -0.094274  
50%         0.509987      -0.064284  
75%         0.662722      -0.036938  
max         1.038294       0.132845  

[8 rows x 64 columns]

In [7]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import Dataset, DataLoader

from sklearn.preprocessing import LabelEncoder

In [8]:
torch.manual_seed(42) # For reproducibility

device = torch.device("cuda")
print("Using device:", device)

Using device: cuda


In [9]:
X = df_train.drop(columns=['target', 'row_ID']).values   # shape: (N, 63)
y = df_train["target"]               # shape: (N,)


In [10]:
X_test = df_test.drop(columns=["row_ID"], errors="ignore").values


In [11]:
'''
X = X.reshape(-1, 21, 3)
X_test  = X_test.reshape(-1, 21, 3)

X = X - X[:, 0:1, :]
X_test  = X_test  - X_test[:, 0:1, :]

X = X.reshape(-1, 63)
X_test  = X_test.reshape(-1, 63)

'''

'\nX = X.reshape(-1, 21, 3)\nX_test  = X_test.reshape(-1, 21, 3)\n\nX = X - X[:, 0:1, :]\nX_test  = X_test  - X_test[:, 0:1, :]\n\nX = X.reshape(-1, 63)\nX_test  = X_test.reshape(-1, 63)\n\n'

In [12]:
'''
# compute on TRAIN only
mean = X.mean(axis=0)
std  = X.std(axis=0)

# replace NaNs BEFORE normalization
X_test = np.where(np.isnan(X_test), mean, X_test)

# now safe std
std_safe = np.where(std < 1e-6, 1.0, std)

# normalize
X = (X - mean) / std_safe
X_test = (X_test - mean) / std_safe

'''

'\n# compute on TRAIN only\nmean = X.mean(axis=0)\nstd  = X.std(axis=0)\n\n# replace NaNs BEFORE normalization\nX_test = np.where(np.isnan(X_test), mean, X_test)\n\n# now safe std\nstd_safe = np.where(std < 1e-6, 1.0, std)\n\n# normalize\nX = (X - mean) / std_safe\nX_test = (X_test - mean) / std_safe\n\n'

In [13]:
#assert not np.isnan(X).any()
#assert not np.isnan(X_test).any()


In [14]:
print(X.mean(), X.std())
print(X_test.mean(),  X_test.std())


0.3128133682739051 0.3108060610725722
nan nan


In [15]:
np.where(np.isnan(X_test).any(axis=0))[0]



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62])

In [16]:
# subtract wrist (landmark 0)
#X = X.reshape(-1, 21, 3)
#X = X - X[:, 0:1, :]
#X = X.reshape(-1, 63)


In [17]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

print(np.unique(y_encoded))  # should be 0 to 11


[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
np.bincount(y_encoded)


array([ 631,  736, 2404,  775, 2807,  915, 3067, 2973, 2854,  729, 3393,
        832])

In [19]:
class_counts = np.bincount(y_encoded)
class_weights = 1.0 / class_counts
class_weights = class_weights / class_weights.sum()  # normalize (optional)

class_weights = torch.tensor(class_weights, dtype=torch.float32)


In [20]:
X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y_encoded, dtype=torch.long)

In [21]:
class ASLDataset(Dataset):
    def __init__(self, X, y=None):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        if self.y is not None:
            return self.X[idx], self.y[idx]
        return self.X[idx]


In [22]:
dataset = ASLDataset(X_tensor, y_tensor)

#A Dataset answers two questions:

#How many samples?

#What is sample i?

In [23]:
loader = DataLoader(
    dataset,
    batch_size=32,
    shuffle=True
)


In [24]:
class ASLNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(63, 64),
           # nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Dropout(0.15),

            nn.Linear(64, 32),
          #  nn.BatchNorm1d(32),
            nn.ReLU(),
            nn.Dropout(0.15),

            nn.Linear(32, 12)
        )

    def forward(self, x):
        return self.net(x)



In [25]:
model = ASLNet()


In [26]:
criterion = nn.CrossEntropyLoss()

#crossentropyloss applies softmax internally

In [27]:
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [28]:
epochs = 500

for epoch in range(epochs):
    model.train()
    total_loss = 0

    for X_batch, y_batch in loader:
        optimizer.zero_grad()          # clear old gradients

        logits = model(X_batch)        # forward pass
        loss = criterion(logits, y_batch)

        loss.backward()                # backprop
        optimizer.step()               # update weights

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss/len(loader):.4f}")


Epoch 1, Loss: 1.4949
Epoch 2, Loss: 0.6461
Epoch 3, Loss: 0.4458
Epoch 4, Loss: 0.3510
Epoch 5, Loss: 0.2955
Epoch 6, Loss: 0.2578
Epoch 7, Loss: 0.2288
Epoch 8, Loss: 0.2089
Epoch 9, Loss: 0.1909
Epoch 10, Loss: 0.1840
Epoch 11, Loss: 0.1720
Epoch 12, Loss: 0.1600
Epoch 13, Loss: 0.1581
Epoch 14, Loss: 0.1520
Epoch 15, Loss: 0.1464
Epoch 16, Loss: 0.1367
Epoch 17, Loss: 0.1355
Epoch 18, Loss: 0.1300
Epoch 19, Loss: 0.1266
Epoch 20, Loss: 0.1226
Epoch 21, Loss: 0.1202
Epoch 22, Loss: 0.1180
Epoch 23, Loss: 0.1127
Epoch 24, Loss: 0.1103
Epoch 25, Loss: 0.1081
Epoch 26, Loss: 0.1064
Epoch 27, Loss: 0.1011
Epoch 28, Loss: 0.0987
Epoch 29, Loss: 0.1008
Epoch 30, Loss: 0.0979
Epoch 31, Loss: 0.0971
Epoch 32, Loss: 0.0959
Epoch 33, Loss: 0.0914
Epoch 34, Loss: 0.0936
Epoch 35, Loss: 0.0940
Epoch 36, Loss: 0.0882
Epoch 37, Loss: 0.0914
Epoch 38, Loss: 0.0899
Epoch 39, Loss: 0.0857
Epoch 40, Loss: 0.0817
Epoch 41, Loss: 0.0858
Epoch 42, Loss: 0.0824
Epoch 43, Loss: 0.0814
Epoch 44, Loss: 0.08

In [29]:
print("ENCODER CLASSES:", le.classes_)


ENCODER CLASSES: ['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L']


In [30]:
X_test = df_test.drop(columns=["row_ID"], errors="ignore").values
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)

test_dataset = ASLDataset(X_test_tensor)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)


In [31]:
model.eval()
predictions = []

with torch.no_grad():
    for X_batch in test_loader:
        logits = model(X_batch)
        preds = torch.argmax(logits, dim=1)
        predictions.extend(preds.cpu().numpy())


In [32]:
print(preds[:20])
print(le.inverse_transform(preds[:20]))


tensor([ 5,  6, 10,  8,  1,  2, 11,  8,  9,  0, 10,  1,  3,  0])
['F' 'G' 'K' 'I' 'B' 'C' 'L' 'I' 'J' 'A' 'K' 'B' 'D' 'A']


In [33]:
pred_labels = le.inverse_transform(predictions)


In [34]:
submission = pd.read_csv("/kaggle/input/sahaay-dc-training-assignment-8-part-2/sample_submission.csv")
submission["Target"] = pred_labels
submission.to_csv("submission.csv", index=False)
